import type { AccountReport, PipelineRow } from "@/lib/types";

/**
 * Visibly synthetic Snapfresh fixtures.
 *
 * Used only when the browser environment is not configured. Everything here is
 * fabricated for demonstration and is badged SYNTHETIC in the UI.
 */

const ACCOUNT_ID = "00000000-0000-4000-8000-000000000001";
const RUN_ID = "00000000-0000-4000-8000-0000000000a1";
const SEQ_ID = "00000000-0000-4000-8000-0000000000b1";

const src = (n: number) => `00000000-0000-4000-8000-0000000001${String(n).padStart(2, "0")}`;
const dish = (n: number) => `00000000-0000-4000-8000-0000000002${String(n).padStart(2, "0")}`;
const contact = (n: number) => `00000000-0000-4000-8000-0000000003${String(n).padStart(2, "0")}`;
const msg = (n: number) => `00000000-0000-4000-8000-0000000004${String(n).padStart(2, "0")}`;

const hoursAgo = (h: number) => new Date(Date.now() - h * 3600_000).toISOString();

export const fixturePipeline: PipelineRow[] = [
  {
    account_id: ACCOUNT_ID,
    company_name: "Snapfresh",
    domain: "snapfresh.com.au",
    score: 78,
    tier: "A",
    stage: "draft_ready",
    latest_run_status: "draft_ready",
    suppressed: false,
    engaged: true,
    updated_at: hoursAgo(2),
    estimated_opportunity: 184000,
    active_sequences: 1,
  },
  {
    account_id: "00000000-0000-4000-8000-000000000002",
    company_name: "Harvest Table Foods",
    domain: "harvesttable.example",
    score: 61,
    tier: "B",
    stage: "scored",
    latest_run_status: "failed_partial",
    suppressed: false,
    engaged: false,
    updated_at: hoursAgo(9),
    estimated_opportunity: 74000,
    active_sequences: 0,
  },
  {
    account_id: "00000000-0000-4000-8000-000000000003",
    company_name: "Coastline Catering Co",
    domain: "coastlinecatering.example",
    score: 44,
    tier: "C",
    stage: "review",
    latest_run_status: "evidence_collected",
    suppressed: true,
    engaged: false,
    updated_at: hoursAgo(30),
    estimated_opportunity: null,
    active_sequences: 0,
  },
];

export const fixtureReport: AccountReport = {
  account: {
    id: ACCOUNT_ID,
    company_name: "Snapfresh",
    domain: "snapfresh.com.au",
    parent_company: "Snapfresh Group Pty Ltd (synthetic)",
    segment: "Chilled ready-meal manufacturer",
    service_area: "VIC, NSW, QLD metro distribution",
    service_area_fit: "Strong — overlaps Knoxx east-coast cold chain",
    scale_signals: "Two production sites, ~140 staff, national grocery listings",
    created_at: hoursAgo(240),
    updated_at: hoursAgo(2),
  },
  runs: [
    {
      id: RUN_ID,
      account_id: ACCOUNT_ID,
      status: "draft_ready",
      stage: "draft_ready",
      error_summary: null,
      created_at: hoursAgo(4),
      updated_at: hoursAgo(2),
    },
    {
      id: "00000000-0000-4000-8000-0000000000a2",
      account_id: ACCOUNT_ID,
      status: "failed_partial",
      stage: "evidence_collected",
      error_summary: "3 of 11 product pages timed out; scoring ran on partial evidence.",
      created_at: hoursAgo(72),
      updated_at: hoursAgo(71),
    },
  ],
  sources: [
    {
      id: src(1),
      account_id: ACCOUNT_ID,
      url: "https://snapfresh.com.au/products/chilled-meals",
      source_type: "product_page",
      retrieved_at: hoursAgo(4),
      retained_passage:
        "Our chilled range includes butter chicken, beef massaman and creamy mushroom pasta, produced weekly at our Dandenong facility.",
      source_key: "snapfresh:products:chilled-meals",
    },
    {
      id: src(2),
      account_id: ACCOUNT_ID,
      url: "https://snapfresh.com.au/about",
      source_type: "about_page",
      retrieved_at: hoursAgo(4),
      retained_passage:
        "Snapfresh operates two production sites and supplies chilled meals to national grocery and food-service channels.",
      source_key: "snapfresh:about",
    },
    {
      id: src(3),
      account_id: ACCOUNT_ID,
      url: "https://example-trade-press.test/snapfresh-expansion",
      source_type: "trade_press",
      retrieved_at: hoursAgo(5),
      retained_passage:
        "The manufacturer flagged a second chilled line commissioning in the coming financial year.",
      source_key: "trade:snapfresh:expansion",
    },
  ],
  findings: [
    {
      id: "f1",
      account_id: ACCOUNT_ID,
      category: "Product",
      statement: "Produces chilled sauce-forward ready meals in weekly production runs.",
      label: "observed",
      source_id: src(1),
    },
    {
      id: "f2",
      account_id: ACCOUNT_ID,
      category: "Scale",
      statement: "Weekly chilled volume is consistent with a mid-size manufacturer.",
      label: "inferred",
      source_id: src(2),
    },
    {
      id: "f3",
      account_id: ACCOUNT_ID,
      category: "Timing",
      statement: "A second line commissioning could create a reformulation window.",
      label: "hypothesis",
      source_id: src(3),
    },
  ],
  dishes: [
    {
      id: dish(1),
      account_id: ACCOUNT_ID,
      name: "Butter Chicken",
      description: "Chilled 350g single-serve",
      source_id: src(1),
    },
    {
      id: dish(2),
      account_id: ACCOUNT_ID,
      name: "Beef Massaman",
      description: "Chilled 350g single-serve",
      source_id: src(1),
    },
    {
      id: dish(3),
      account_id: ACCOUNT_ID,
      name: "Creamy Mushroom Pasta",
      description: "Chilled 400g single-serve",
      source_id: src(1),
    },
  ],
  ingredients: [
    {
      id: "ri1",
      dish_id: dish(1),
      ingredient_name: "Cream powder",
      role: "sauce base",
      source_id: src(1),
    },
    {
      id: "ri2",
      dish_id: dish(1),
      ingredient_name: "Tomato paste",
      role: "sauce base",
      source_id: src(1),
    },
    {
      id: "ri3",
      dish_id: dish(2),
      ingredient_name: "Coconut milk powder",
      role: "sauce base",
      source_id: src(1),
    },
    {
      id: "ri4",
      dish_id: dish(3),
      ingredient_name: "Cream powder",
      role: "sauce base",
      source_id: src(1),
    },
  ],
  matches: [
    {
      id: "m1",
      account_id: ACCOUNT_ID,
      catalog_item_id: "k1",
      knoxx_item_name: "Knoxx Dairy Cream Powder 26%",
      match_reason: "Cream powder appears as the sauce base in two observed chilled SKUs.",
      confidence: 0.82,
      ingredient_name: "Cream powder",
    },
    {
      id: "m2",
      account_id: ACCOUNT_ID,
      catalog_item_id: "k2",
      knoxx_item_name: "Knoxx Coconut Milk Powder",
      match_reason: "Massaman sauce base observed on the chilled product page.",
      confidence: 0.64,
      ingredient_name: "Coconut milk powder",
    },
  ],
  forecasts: [
    {
      id: "q1",
      account_id: ACCOUNT_ID,
      ingredient_match_id: "m1",
      formula_inputs: {
        units_per_week: 42000,
        inclusion_rate_pct: 3.1,
        sku_coverage: 2,
        evidence_basis: "observed product range + inferred run size",
      },
      weekly_low: 980,
      weekly_base: 1302,
      weekly_high: 1610,
      monthly_low: 4250,
      monthly_base: 5645,
      monthly_high: 6980,
      annual_low: 51000,
      annual_base: 67700,
      annual_high: 83700,
      unit: "kg",
    },
    {
      id: "q2",
      account_id: ACCOUNT_ID,
      ingredient_match_id: "m2",
      formula_inputs: { inclusion_rate_pct: null, units_per_week: null },
      weekly_low: null,
      weekly_base: null,
      weekly_high: null,
      monthly_low: null,
      monthly_base: null,
      monthly_high: null,
      annual_low: null,
      annual_base: null,
      annual_high: null,
      unit: "kg",
    },
  ],
  score: {
    id: "s1",
    account_id: ACCOUNT_ID,
    total: 78,
    tier: "A",
    components: {
      ingredient_fit: 26,
      volume_potential: 22,
      service_area_fit: 16,
      buying_signal: 10,
      evidence_quality: 9,
    },
    risk_penalty: -5,
    reasons: [
      "Two Knoxx catalogue items map to observed sauce bases.",
      "East-coast distribution overlaps existing cold chain.",
      "Penalty applied: one forecast lacks inclusion-rate evidence.",
    ],
    rule_version: "qualification_rules v3 (synthetic)",
  },
  contacts: [
    {
      id: contact(1),
      account_id: ACCOUNT_ID,
      full_name: "Dana Whitcombe",
      title: "Head of Product Development",
      persona: "Technical champion",
      email: "dana.whitcombe@snapfresh.example",
      email_status: "verified",
      is_synthetic: true,
      activation_eligible: true,
    },
    {
      id: contact(2),
      account_id: ACCOUNT_ID,
      full_name: "Marcus Iyer",
      title: "Procurement Manager",
      persona: "Economic buyer",
      email: "marcus.iyer@snapfresh.example",
      email_status: "verified",
      is_synthetic: true,
      activation_eligible: true,
    },
    {
      id: contact(3),
      account_id: ACCOUNT_ID,
      full_name: "Priya Nandakumar",
      title: "Operations Director",
      persona: "Influencer",
      email: "priya.n@snapfresh.example",
      email_status: "catch_all",
      is_synthetic: true,
      activation_eligible: false,
    },
  ],
  rankings: [
    {
      id: "r1",
      contact_id: contact(1),
      account_id: ACCOUNT_ID,
      rank: 1,
      components: { persona_fit: 9, seniority: 7, reachability: 8 },
      explanation: "Owns reformulation decisions for chilled sauce bases.",
    },
    {
      id: "r2",
      contact_id: contact(2),
      account_id: ACCOUNT_ID,
      rank: 2,
      components: { persona_fit: 8, seniority: 8, reachability: 6 },
      explanation: "Controls ingredient supplier contracts and pricing.",
    },
    {
      id: "r3",
      contact_id: contact(3),
      account_id: ACCOUNT_ID,
      rank: 3,
      components: { persona_fit: 6, seniority: 7, reachability: 4 },
      explanation: "Consulted on line capacity; catch-all address limits activation.",
    },
  ],
  history: [
    {
      id: "h1",
      account_id: ACCOUNT_ID,
      contact_id: contact(1),
      summary: "Similar chilled manufacturer replied to an ingredient-fit opener.",
      outcome: "positive_reply",
      is_synthetic: true,
      occurred_at: hoursAgo(1400),
    },
  ],
  sequences: [
    {
      id: SEQ_ID,
      account_id: ACCOUNT_ID,
      contact_id: contact(1),
      status: "draft",
      created_at: hoursAgo(2),
    },
  ],
  messages: [
    {
      id: msg(1),
      sequence_id: SEQ_ID,
      day_offset: 0,
      subject: "Cream powder consistency across your chilled range",
      body: "Hi Dana,\n\nYour chilled range lists butter chicken and creamy mushroom pasta, both cream-powder sauce bases. We supply a 26% dairy cream powder that holds emulsion through chilled shelf life.\n\nWorth a short call?",
      status: "draft",
      approved_claims: ["Two observed SKUs use a cream-powder sauce base."],
      evidence_refs: [src(1)],
      intended_recipient: "dana.whitcombe@snapfresh.example",
    },
    {
      id: msg(2),
      sequence_id: SEQ_ID,
      day_offset: 3,
      subject: "Re: cream powder consistency",
      body: "Hi Dana,\n\nFollowing up with the inclusion-rate range we modelled for your weekly run size.",
      status: "draft",
      approved_claims: ["Weekly volume estimate is a range, not a point figure."],
      evidence_refs: [src(2)],
      intended_recipient: "dana.whitcombe@snapfresh.example",
    },
    {
      id: msg(3),
      sequence_id: SEQ_ID,
      day_offset: 7,
      subject: "Massaman base — coconut milk powder",
      body: "Hi Dana,\n\nOne more: your massaman base is a candidate for our coconut milk powder. We do not yet have inclusion-rate evidence, so I would rather ask than guess.",
      status: "draft",
      approved_claims: ["Coconut milk powder forecast is insufficient_evidence."],
      evidence_refs: [src(1)],
      intended_recipient: "dana.whitcombe@snapfresh.example",
    },
    {
      id: msg(4),
      sequence_id: SEQ_ID,
      day_offset: 12,
      subject: "Closing the loop",
      body: "Hi Dana,\n\nClosing the loop — happy to send the spec sheets and step back if the timing is wrong.",
      status: "draft",
      approved_claims: [],
      evidence_refs: [],
      intended_recipient: "dana.whitcombe@snapfresh.example",
    },
  ],
  events: [
    {
      id: "e1",
      account_id: ACCOUNT_ID,
      contact_id: contact(1),
      message_id: msg(1),
      event_type: "cta_click",
      provider: "manual_demo",
      created_at: hoursAgo(20),
      payload: {},
    },
    {
      id: "e2",
      account_id: ACCOUNT_ID,
      contact_id: contact(1),
      message_id: msg(1),
      event_type: "positive_reply",
      provider: "manual_demo",
      created_at: hoursAgo(3),
      payload: {},
    },
  ],
  suppressions: [
    {
      id: "sp1",
      account_id: ACCOUNT_ID,
      contact_id: null,
      scope: "account",
      reason: "Positive reply recorded — all other contacts paused by the server.",
      created_at: hoursAgo(3),
    },
  ],
};

export const FIXTURE_ACCOUNT_ID = ACCOUNT_ID;
export const FIXTURE_RUN_ID = RUN_ID;
