// Mock evaluation data simulating Model 1 output
export const mockEvaluationResult = {
  call_metadata: {
    call_id: "CALL123456",
    call_type: "inbound",
    customer_type: "existing",
    start_time: "2025-01-15T10:30:00Z",
    end_time: "2025-01-15T10:38:45Z",
    duration_seconds: 525,
    language_detected: "english",
    customer_drop_off: false,
  },
  classification_and_tagging: {
    primary_topic: "unauthorized_charge",
    primary_topic_score: 0.89,
    secondary_topics: [{ topic: "billing_dispute", score: 0.35 }],
    primary_intent: "dispute_charge",
    primary_intent_confidence: 0.92,
    secondary_intent: "request_refund",
    secondary_intent_confidence: 0.68,
    team_assignments: [
      {
        team_id: "fraud_team",
        team_name: "Fraud & Security Team",
        role: "primary_owner",
        reason: "RAG mapping for unauthorized_charge: primary owner is fraud_team",
        rag_confidence: 1.0,
      },
      {
        team_id: "billing_team",
        team_name: "Billing & Finance Team",
        role: "secondary_owner",
        reason: "RAG mapping: refund processing involvement",
        rag_confidence: 1.0,
      },
      {
        team_id: "cx_team",
        team_name: "Customer Experience Team",
        role: "notify",
        reason: "RAG mapping: customer experience monitoring",
        rag_confidence: 1.0,
      },
    ],
    escalation_triggered: true,
    escalation_reason: "Unauthorized charge triggers automatic leadership notification per security policy",
    root_causes: [
      {
        cause: "third_party_failure",
        confidence: 0.85,
        evidence: "Customer stated: 'I was charged $49.99 and I didn't authorize it'",
        impact_level: "high",
      },
    ],
    real_time_insights: [
      {
        insight_id: "INS_2025011510001",
        insight_type: "fraud_alert",
        title: "Unauthorized Charge - Immediate Fraud Investigation Required",
        description: "Customer reports $49.99 unauthorized charge from Merchant XYZ",
        urgency: "high",
        affected_teams: ["fraud_team", "billing_team", "cx_team"],
        action_required: true,
        recommended_actions: [
          "Initiate fraud investigation immediately",
          "Monitor for similar charges from Merchant XYZ",
          "Alert fraud prevention system",
        ],
      },
    ],
  },
  dimension_1_understanding_accuracy_compliance: {
    problem_capture: { label: "clear", confidence: 0.95 },
    information_accuracy: { label: "correct", confidence: 0.98 },
    compliance: { label: "pass", violations: [], confidence: 1.0 },
    product_service_mapping: { label: "correct", confidence: 0.92 },
    score: 34.65,
    alerts: [],
  },
  dimension_2_communication_clarity: {
    greeting: { label: "present", tone: "warm", confidence: 1.0 },
    language_alignment: { label: "aligned", confidence: 1.0 },
    speech_clarity: { label: "clear", issues: [], confidence: 0.98 },
    listening: { interruptions: 0, forced_repetitions: 0, label: "good" },
    score: 19.8,
    alerts: [],
  },
  dimension_3_responsiveness_efficiency: {
    response_latency: { average_turn_delay_sec: 2, max_turn_delay_sec: 4 },
    hold_handling: { label: "appropriate", hold_duration_sec: 28, confidence: 1.0 },
    dead_air: { total_duration_sec: 0, label: "acceptable" },
    score: 15.0,
    alerts: [],
  },
  dimension_4_emotional_intelligence: {
    customer_emotion_start: "frustrated",
    customer_emotion_end: "satisfied",
    emotion_shift: "improved",
    empathy_markers: { detected: true, phrases: ["I understand your concern", "I apologize for the inconvenience"] },
    agent_patience_level: { label: "high", confidence: 0.95 },
    score: 14.85,
    alerts: [],
  },
  dimension_5_resolution_closure: {
    solution_correctness: { label: "correct", confidence: 0.98 },
    next_steps_clarity: { label: "clear", eta_provided: true, confidence: 1.0 },
    customer_confirmation: { label: "confirmed", phrases: ["yes, that sounds good", "thank you"] },
    closure_quality: { label: "proper", confidence: 1.0 },
    score: 15.0,
    alerts: [],
  },
  weighted_overall_score: 99.3,
  global_alerts: [],
  summary: {
    strengths: [
      "Perfect verification and compliance adherence",
      "Strong empathy with positive emotional outcome",
      "Clear resolution with proper fraud escalation",
    ],
    improvements: [],
    critical_issues: [],
    one_line_summary: "Outstanding fraud dispute handling with perfect compliance, empathy, and resolution clarity.",
  },
};

export const mockTranscript = [
  { time: "00:00:05", speaker: "Agent", text: "Thank you for calling ABC Support, my name is Sarah. How may I assist you today?" },
  { time: "00:00:12", speaker: "Customer", text: "Hi Sarah, I'm calling because I noticed a charge on my account that I definitely didn't make." },
  { time: "00:00:20", speaker: "Agent", text: "I understand your concern, and I'm here to help. Before we proceed, may I verify your account? Can you please provide your account number and the last four digits of your registered phone?" },
  { time: "00:00:35", speaker: "Customer", text: "Sure, my account number is 987654 and the last four digits are 1234." },
  { time: "00:00:42", speaker: "Agent", text: "Thank you for that verification. I can see your account now. Could you tell me more about the charge you're disputing?" },
  { time: "00:00:52", speaker: "Customer", text: "I was charged $49.99 by something called 'Merchant XYZ' on January 10th. I have no idea what this is - I've never heard of them." },
  { time: "00:01:08", speaker: "Agent", text: "I apologize for the inconvenience this has caused. Let me look into this transaction for you. Could you please hold for just a moment while I review the details?" },
  { time: "00:01:18", speaker: "Customer", text: "Yes, that's fine." },
  { time: "00:01:48", speaker: "Agent", text: "Thank you for holding. I've reviewed the transaction, and I can see this charge does appear unusual. I'm going to initiate a dispute on your behalf and also flag this for our fraud investigation team." },
  { time: "00:02:05", speaker: "Customer", text: "Okay, that sounds good. Will I get my money back?" },
  { time: "00:02:12", speaker: "Agent", text: "Yes, we'll issue a provisional credit to your account within 24-48 hours while we complete the investigation. The full investigation typically takes 5-7 business days." },
  { time: "00:02:28", speaker: "Customer", text: "That's a relief. Thank you so much for your help, Sarah." },
  { time: "00:02:34", speaker: "Agent", text: "You're very welcome! Is there anything else I can assist you with today?" },
  { time: "00:02:40", speaker: "Customer", text: "No, that's all. Thank you again!" },
  { time: "00:02:45", speaker: "Agent", text: "Thank you for calling ABC Support. Have a wonderful day!" },
];

// Mock dashboard data
export const mockDashboardCalls = [
  {
    call_id: "CALL123456",
    date: "2025-01-15T10:30:00Z",
    customer_type: "existing",
    primary_topic: "unauthorized_charge",
    model_score: 99.3,
    escalation: true,
    root_cause: "third_party_failure",
    assigned_team: "Fraud & Security Team",
    emotion_shift: "frustrated → satisfied",
  },
  {
    call_id: "CALL123457",
    date: "2025-01-15T11:15:00Z",
    customer_type: "new",
    primary_topic: "product_bug",
    model_score: 87.5,
    escalation: false,
    root_cause: "product_defect",
    assigned_team: "Technical Support",
    emotion_shift: "confused → relieved",
  },
  {
    call_id: "CALL123458",
    date: "2025-01-15T12:00:00Z",
    customer_type: "existing",
    primary_topic: "billing_dispute",
    model_score: 92.1,
    escalation: false,
    root_cause: "pricing_confusion",
    assigned_team: "Billing & Finance Team",
    emotion_shift: "irritated → satisfied",
  },
  {
    call_id: "CALL123459",
    date: "2025-01-15T13:30:00Z",
    customer_type: "existing",
    primary_topic: "cancellation_request",
    model_score: 78.4,
    escalation: true,
    root_cause: "policy_gap",
    assigned_team: "CX Team",
    emotion_shift: "frustrated → disappointed",
  },
  {
    call_id: "CALL123460",
    date: "2025-01-15T14:45:00Z",
    customer_type: "new",
    primary_topic: "refund_request",
    model_score: 95.2,
    escalation: false,
    root_cause: "customer_misunderstanding",
    assigned_team: "Billing & Finance Team",
    emotion_shift: "anxious → relieved",
  },
  {
    call_id: "CALL123461",
    date: "2025-01-14T09:00:00Z",
    customer_type: "existing",
    primary_topic: "service_downtime",
    model_score: 88.9,
    escalation: true,
    root_cause: "system_failure",
    assigned_team: "Technical Support",
    emotion_shift: "angry → neutral",
  },
  {
    call_id: "CALL123462",
    date: "2025-01-14T10:30:00Z",
    customer_type: "existing",
    primary_topic: "account_access",
    model_score: 91.7,
    escalation: false,
    root_cause: "agent_error",
    assigned_team: "CX Team",
    emotion_shift: "confused → satisfied",
  },
  {
    call_id: "CALL123463",
    date: "2025-01-14T14:00:00Z",
    customer_type: "new",
    primary_topic: "feature_request",
    model_score: 96.8,
    escalation: false,
    root_cause: "N/A",
    assigned_team: "Product Team",
    emotion_shift: "neutral → happy",
  },
];

export const mockKPIs = {
  totalCalls: 248,
  issuesDetected: 42,
  complianceFailures: 3,
  incorrectSolutions: 7,
  escalationsTriggered: 28,
  averageScore: 91.4,
  emotionImprovement: 78,
};

export const mockTopicDistribution = [
  { name: "Billing Dispute", value: 45 },
  { name: "Product Bug", value: 32 },
  { name: "Unauthorized Charge", value: 28 },
  { name: "Refund Request", value: 24 },
  { name: "Account Access", value: 22 },
  { name: "Service Downtime", value: 18 },
  { name: "Cancellation", value: 15 },
  { name: "Feature Request", value: 12 },
];

export const mockRootCauseDistribution = [
  { name: "Product Defect", value: 35 },
  { name: "Policy Gap", value: 28 },
  { name: "Agent Error", value: 22 },
  { name: "System Failure", value: 18 },
  { name: "Third Party Failure", value: 15 },
  { name: "Customer Misunderstanding", value: 12 },
];

export const mockTeamDistribution = [
  { name: "CX Team", value: 65 },
  { name: "Billing Team", value: 52 },
  { name: "Technical Support", value: 48 },
  { name: "Fraud Team", value: 32 },
  { name: "Product Team", value: 28 },
  { name: "Operations", value: 23 },
];

export const teams = [
  "CX Team",
  "Billing Team",
  "Product Team",
  "Fraud Team",
  "Technical Support",
  "Operations",
  "Leadership",
];

export const bpos = ["BPO 1", "BPO 2", "BPO 3"];

export const rootCauses = [
  "product_defect",
  "unclear_documentation",
  "agent_error",
  "system_failure",
  "policy_gap",
  "process_inefficiency",
  "communication_breakdown",
  "training_gap",
  "third_party_failure",
  "customer_misunderstanding",
  "technical_limitation",
  "pricing_confusion",
  "sop_non_compliance",
  "integration_failure",
  "data_quality_issue",
];
